name: deploy to production
on:
  push:
    branches: [ main ]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
    - name: clone the repo
      uses: actions/checkout@v2

    - name: login to docker
      uses: docker/login-action@v2
      with:
        username : ${{secrets.DOCKER_USERNAME}}
        password: ${{secrets.DOCKER_PASSWORD}}
    
    - name: push the image to doker hub
      uses: docker/build-push-action@v4
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: asimdockeraga/ci-cd:${{github.sha}}
    
    - name: sssshssss into the VM
      run: |
        echo "${{ secrets.DOCKER_PEM }}" > asim.pem
        chmod 600 asim.pem
        ssh -o StrictHostKeyChecking=no -i asim.pem ubuntu@15.206.88.153 -t "docker stop user_app && docker rm user_app && docker run --name user_app -d -p 3000:3000 asimdockeraga/ci-cd:${{github.sha}}"

